adding new doc how to order for someone else
ByteInternet/hypernode-docs-next pull request #222
Opened 2023-11-23 15:20 UTC by Niutah

2023-11-23 15:30 UTC, alejandrogarza approved these changes

2023-11-23 15:31 UTC, hrithikkothari1234 approved these changes

2023-11-23 15:39 UTC, tdgroot requested changes

2023-11-23 15:39 UTC, tdgroot commented on docs/services/control-panel/how-to-order-hypernode-for-someone-else.md
Filename and title should be 'a Hypernode', not 'Hypernode'.

2023-11-23 15:44 UTC, Niutah commented on docs/services/control-panel/how-to-order-hypernode-for-someone-else.md
oh that's picky! ;p

2023-11-24 11:18 UTC, tdgroot approved these changes

2023-11-24 11:19 UTC, merged