400 mins free brancher allowance
ByteInternet/hypernode-docs-next pull request #229
Opened 2023-12-19 12:35 UTC by ikidnapmyself

Jira: https://teamdotblue.atlassian.net/browse/NL3WEB3-1470

> ### Free Usage Allowance: First 400 Minutes per Hypernode
> 
> You are entitled to a complimentary allocation of 400 minutes for each Hypernode. This means
> you will not be charged for your Brancher minutes usage until it surpasses the threshold of **400 minutes per month
> per Hypernode**, applicable throughout the year 2024. We value your usage and aim to ensure you enjoy the benefits of > our service without incurring additional costs within this specified limit.

2023-12-19 12:56 UTC, martijneichelsheim requested changes

2024-01-18 10:06 UTC, iryszawa commented
Placement of the paragraph is good :) 

Small adjustments to the text:

All Combell Openstack and AWS plans (Falcons and Eagles) include 400 complimentary Brancher minutes for each Hypernode as part of the base package. This means you will not be charged for your Brancher minutes usage until it surpasses the threshold of 400 minutes per month per Hypernode. We aim to ensure that you enjoy the benefits of our service without incurring additional costs within this specified limit.

2024-01-18 12:04 UTC, tdgroot requested changes
Did you format the document in pycharm or something? :sweat_smile:

2024-01-18 12:04 UTC, tdgroot commented on docs/hypernode-platform/tools/hypernode-brancher.md
> +html_meta:
Need to indent these keys properly, see other articles for example

2024-01-18 12:04 UTC, tdgroot commented on docs/hypernode-platform/tools/hypernode-brancher.md
> +- /en/support/solutions/articles/48001227297-hypernode-brancher/
This is also badly formatted

2024-01-18 12:06 UTC, ikidnapmyself commented
@tdgroot i wrote in pycharm then i use mdformat. I also test and build locally with ./bin/ tools

2024-01-18 15:35 UTC, hrithikkothari1234 approved these changes

2024-01-23 13:13 UTC, tdgroot approved these changes

2024-01-23 13:13 UTC, merged